name: aiml_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  google_fonts: ^6.3.3
  provider: ^6.0.7
  photo_manager: ^3.0.0
  image_picker: ^1.0.4
  http: ^1.2.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/aesthetic-predictor.png
    - assets/images/slay3.png
    - assets/images/slay2.png
    - assets/images/slay6.png

  # If you later add more images, just include the folder:
  # - assets/images/
